-- ---------------------------------------------------------------------------
-- VerifySMS — database tables for migrations 0003 and 0004
--
--   core/migrations/0003_smsmessage.py         -> permanent SMS inbox
--   core/migrations/0004_broadcast_notification.py -> admin broadcast messages
--
-- This is the exact PostgreSQL DDL Django would run, generated by Django's own
-- schema editor. Run it ONLY if you cannot run
--   python manage.py migrate
-- against the Supabase database (for example when the Vercel environment has
-- no shell and the DB password is not available).
--
-- How to use it:
--   1. Supabase dashboard -> SQL Editor -> New query.
--   2. Paste this whole file and Run.
--   3. Deploy the matching code afterwards.
--
-- Safe to run more than once: every statement is guarded. If you already ran
-- the earlier version of this file (0003 only), running it again is harmless —
-- the 0003 half is skipped and the 0004 half is added.
-- ---------------------------------------------------------------------------

BEGIN;

-- ═══════════════════════════════════════════════════════════════════════════
-- 0003 — permanent SMS inbox
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. The table itself.
CREATE TABLE IF NOT EXISTS "core_smsmessage" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "order_id" bigint NOT NULL,
    "provider_message_id" varchar(64) NOT NULL,
    "sender" varchar(100) NOT NULL,
    "text" text NOT NULL,
    "code" varchar(50) NOT NULL,
    "provider_date" varchar(64) NOT NULL,
    "created_at" timestamp with time zone NOT NULL
);

-- 2. Link each message to its order. Deleting an order drops its messages.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'core_smsmessage_order_id_10b1eb41_fk_core_order_id'
    ) THEN
        ALTER TABLE "core_smsmessage"
            ADD CONSTRAINT "core_smsmessage_order_id_10b1eb41_fk_core_order_id"
            FOREIGN KEY ("order_id") REFERENCES "core_order" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

-- 3. One row per provider message id, per order. Requests without an id skip
--    the constraint, which is what lets text-only messages be de-duplicated
--    in application code instead.
CREATE UNIQUE INDEX IF NOT EXISTS "uniq_order_provider_sms"
    ON "core_smsmessage" ("order_id", "provider_message_id")
    WHERE NOT ("provider_message_id" = '');

-- 4. Index the foreign key so the inbox page is fast on busy orders.
CREATE INDEX IF NOT EXISTS "core_smsmessage_order_id_10b1eb41"
    ON "core_smsmessage" ("order_id");

-- 5. Record the migration as applied. Without this, a later
--    `manage.py migrate` would try to create the table again and fail.
INSERT INTO django_migrations (app, name, applied)
SELECT 'core', '0003_smsmessage', now()
WHERE NOT EXISTS (
    SELECT 1 FROM django_migrations
    WHERE app = 'core' AND name = '0003_smsmessage'
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 0004 — admin broadcast messages
-- ═══════════════════════════════════════════════════════════════════════════

-- 6. One row per message an admin sent: the text, who it went to, and how many
--    people received it.
CREATE TABLE IF NOT EXISTS "core_broadcast" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(150) NOT NULL,
    "body" text NOT NULL,
    "level" varchar(10) NOT NULL,
    "target" varchar(12) NOT NULL,
    "recipient_count" integer NOT NULL CHECK ("recipient_count" >= 0),
    "created_at" timestamp with time zone NOT NULL,
    "created_by_id" bigint NULL
);

-- 7. Each recipient's own copy, so read state is per user.
CREATE TABLE IF NOT EXISTS "core_notification" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(150) NOT NULL,
    "body" text NOT NULL,
    "level" varchar(10) NOT NULL,
    "read_at" timestamp with time zone NULL,
    "created_at" timestamp with time zone NOT NULL,
    "broadcast_id" bigint NULL,
    "user_id" bigint NOT NULL
);

-- 8. Foreign keys. Deleting an admin keeps their broadcasts (author goes null);
--    deleting a broadcast removes every user's copy of it; deleting a user
--    removes their own messages.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'core_broadcast_created_by_id_23d9abcb_fk_core_user_id') THEN
        ALTER TABLE "core_broadcast"
            ADD CONSTRAINT "core_broadcast_created_by_id_23d9abcb_fk_core_user_id"
            FOREIGN KEY ("created_by_id") REFERENCES "core_user" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'core_notification_broadcast_id_b92f024d_fk_core_broadcast_id') THEN
        ALTER TABLE "core_notification"
            ADD CONSTRAINT "core_notification_broadcast_id_b92f024d_fk_core_broadcast_id"
            FOREIGN KEY ("broadcast_id") REFERENCES "core_broadcast" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'core_notification_user_id_6e341aac_fk_core_user_id') THEN
        ALTER TABLE "core_notification"
            ADD CONSTRAINT "core_notification_user_id_6e341aac_fk_core_user_id"
            FOREIGN KEY ("user_id") REFERENCES "core_user" ("id")
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

-- 9. Indexes for the admin list, the notification centre and the unread badge.
CREATE INDEX IF NOT EXISTS "core_broadcast_created_by_id_23d9abcb"
    ON "core_broadcast" ("created_by_id");
CREATE INDEX IF NOT EXISTS "core_notification_broadcast_id_b92f024d"
    ON "core_notification" ("broadcast_id");
CREATE INDEX IF NOT EXISTS "core_notification_user_id_6e341aac"
    ON "core_notification" ("user_id");
CREATE INDEX IF NOT EXISTS "notif_user_unread_idx"
    ON "core_notification" ("user_id", "read_at");

-- 10. Book-keeping for 0004.
INSERT INTO django_migrations (app, name, applied)
SELECT 'core', '0004_broadcast_notification', now()
WHERE NOT EXISTS (
    SELECT 1 FROM django_migrations
    WHERE app = 'core' AND name = '0004_broadcast_notification'
);

COMMIT;

-- Sanity check — both tables should come back non-null.
SELECT to_regclass('public.core_smsmessage') AS sms_table;
SELECT to_regclass('public.core_broadcast')  AS broadcast_table;
SELECT to_regclass('public.core_notification') AS notification_table;
