# Generated by Django 5.2.17 on 2026-09-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('sender', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('provider_date', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='core.order')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('order', 'provider_message_id'), name='uniq_order_provider_sms')],
            },
        ),
    ]
